package storage

import (
	"context"
	"database/sql"
	"fmt"

	_ "github.com/go-sql-driver/mysql"
)

// DBConfig holds configuration for connecting to the database
// (used both for sql.DB and sqlc initialization).
//
// The previous implementation used GORM dialectors; we now open a
// standard *sql.DB and hand that off to the generated sqlc queries.
//
// The connection string still includes parseTime=true so timestamp
// columns are handled correctly.
type DBConfig struct {
	DBUser string
	DBPass string
	DBAddr string
	DBPort int
	DBName string
}

// NewStorage creates a new Storage instance using a *sql.DB connection
// and builds the sqlc-generated queries object.
func NewStorage(conf DBConfig, ctx context.Context) (*Storage, error) {
	dsn := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?parseTime=true",
		conf.DBUser, conf.DBPass, conf.DBAddr, conf.DBPort, conf.DBName)

	db, err := sql.Open("mysql", dsn)
	if err != nil {
		return nil, err
	}

	return &Storage{
		DB:      db,
		Queries: New(db),
		ctx:     ctx,
		config:  conf,
	}, nil
}

type Storage struct {
	DB      *sql.DB
	Queries *Queries // generated by sqlc
	ctx     context.Context

	config DBConfig
}

// configureMySQL is no longer used; kept for documentation only.
//
// The DSN format is still important when opening with database/sql.
func configureMySQL(conf DBConfig) string {
	return fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?parseTime=true", conf.DBUser, conf.DBPass, conf.DBAddr, conf.DBPort, conf.DBName)
}

// Close shuts down the underlying *sql.DB connection.
func (s *Storage) Close() error {
	if s.DB == nil {
		return nil
	}
	return s.DB.Close()
}

// CreateDBIfNotExists uses a new connection (without specifying database) to
// create the configured database if it does not already exist.
func (s *Storage) CreateDBIfNotExists() error {
	// open temporary connection to server
	dsn := fmt.Sprintf("%s:%s@tcp(%s:%d)/?parseTime=true",
		s.config.DBUser, s.config.DBPass, s.config.DBAddr, s.config.DBPort)
	tmp, err := sql.Open("mysql", dsn)
	if err != nil {
		return err
	}
	defer tmp.Close()

	_, err = tmp.Exec(fmt.Sprintf("CREATE DATABASE IF NOT EXISTS %s;", s.config.DBName))
	return err
}

// DropDB drops the configured database.
func (s *Storage) DropDB() error {
	_, err := s.DB.Exec(fmt.Sprintf("DROP DATABASE IF EXISTS %s;", s.config.DBName))
	return err
}
