// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"
)

// NewMockDialector creates a new instance of MockDialector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDialector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDialector {
	mock := &MockDialector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDialector is an autogenerated mock type for the Dialector type
type MockDialector struct {
	mock.Mock
}

type MockDialector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDialector) EXPECT() *MockDialector_Expecter {
	return &MockDialector_Expecter{mock: &_m.Mock}
}

// BindVarTo provides a mock function for the type MockDialector
func (_mock *MockDialector) BindVarTo(writer clause.Writer, stmt *gorm.Statement, v interface{}) {
	_mock.Called(writer, stmt, v)
	return
}

// MockDialector_BindVarTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindVarTo'
type MockDialector_BindVarTo_Call struct {
	*mock.Call
}

// BindVarTo is a helper method to define mock.On call
//   - writer clause.Writer
//   - stmt *gorm.Statement
//   - v interface{}
func (_e *MockDialector_Expecter) BindVarTo(writer interface{}, stmt interface{}, v interface{}) *MockDialector_BindVarTo_Call {
	return &MockDialector_BindVarTo_Call{Call: _e.mock.On("BindVarTo", writer, stmt, v)}
}

func (_c *MockDialector_BindVarTo_Call) Run(run func(writer clause.Writer, stmt *gorm.Statement, v interface{})) *MockDialector_BindVarTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 clause.Writer
		if args[0] != nil {
			arg0 = args[0].(clause.Writer)
		}
		var arg1 *gorm.Statement
		if args[1] != nil {
			arg1 = args[1].(*gorm.Statement)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDialector_BindVarTo_Call) Return() *MockDialector_BindVarTo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDialector_BindVarTo_Call) RunAndReturn(run func(writer clause.Writer, stmt *gorm.Statement, v interface{})) *MockDialector_BindVarTo_Call {
	_c.Run(run)
	return _c
}

// DataTypeOf provides a mock function for the type MockDialector
func (_mock *MockDialector) DataTypeOf(field *schema.Field) string {
	ret := _mock.Called(field)

	if len(ret) == 0 {
		panic("no return value specified for DataTypeOf")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(*schema.Field) string); ok {
		r0 = returnFunc(field)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDialector_DataTypeOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DataTypeOf'
type MockDialector_DataTypeOf_Call struct {
	*mock.Call
}

// DataTypeOf is a helper method to define mock.On call
//   - field *schema.Field
func (_e *MockDialector_Expecter) DataTypeOf(field interface{}) *MockDialector_DataTypeOf_Call {
	return &MockDialector_DataTypeOf_Call{Call: _e.mock.On("DataTypeOf", field)}
}

func (_c *MockDialector_DataTypeOf_Call) Run(run func(field *schema.Field)) *MockDialector_DataTypeOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *schema.Field
		if args[0] != nil {
			arg0 = args[0].(*schema.Field)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDialector_DataTypeOf_Call) Return(s string) *MockDialector_DataTypeOf_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDialector_DataTypeOf_Call) RunAndReturn(run func(field *schema.Field) string) *MockDialector_DataTypeOf_Call {
	_c.Call.Return(run)
	return _c
}

// DefaultValueOf provides a mock function for the type MockDialector
func (_mock *MockDialector) DefaultValueOf(field *schema.Field) clause.Expression {
	ret := _mock.Called(field)

	if len(ret) == 0 {
		panic("no return value specified for DefaultValueOf")
	}

	var r0 clause.Expression
	if returnFunc, ok := ret.Get(0).(func(*schema.Field) clause.Expression); ok {
		r0 = returnFunc(field)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clause.Expression)
		}
	}
	return r0
}

// MockDialector_DefaultValueOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultValueOf'
type MockDialector_DefaultValueOf_Call struct {
	*mock.Call
}

// DefaultValueOf is a helper method to define mock.On call
//   - field *schema.Field
func (_e *MockDialector_Expecter) DefaultValueOf(field interface{}) *MockDialector_DefaultValueOf_Call {
	return &MockDialector_DefaultValueOf_Call{Call: _e.mock.On("DefaultValueOf", field)}
}

func (_c *MockDialector_DefaultValueOf_Call) Run(run func(field *schema.Field)) *MockDialector_DefaultValueOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *schema.Field
		if args[0] != nil {
			arg0 = args[0].(*schema.Field)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDialector_DefaultValueOf_Call) Return(expression clause.Expression) *MockDialector_DefaultValueOf_Call {
	_c.Call.Return(expression)
	return _c
}

func (_c *MockDialector_DefaultValueOf_Call) RunAndReturn(run func(field *schema.Field) clause.Expression) *MockDialector_DefaultValueOf_Call {
	_c.Call.Return(run)
	return _c
}

// Explain provides a mock function for the type MockDialector
func (_mock *MockDialector) Explain(sql string, vars ...interface{}) string {
	var tmpRet mock.Arguments
	if len(vars) > 0 {
		tmpRet = _mock.Called(sql, vars)
	} else {
		tmpRet = _mock.Called(sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Explain")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) string); ok {
		r0 = returnFunc(sql, vars...)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDialector_Explain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Explain'
type MockDialector_Explain_Call struct {
	*mock.Call
}

// Explain is a helper method to define mock.On call
//   - sql string
//   - vars ...interface{}
func (_e *MockDialector_Expecter) Explain(sql interface{}, vars ...interface{}) *MockDialector_Explain_Call {
	return &MockDialector_Explain_Call{Call: _e.mock.On("Explain",
		append([]interface{}{sql}, vars...)...)}
}

func (_c *MockDialector_Explain_Call) Run(run func(sql string, vars ...interface{})) *MockDialector_Explain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockDialector_Explain_Call) Return(s string) *MockDialector_Explain_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDialector_Explain_Call) RunAndReturn(run func(sql string, vars ...interface{}) string) *MockDialector_Explain_Call {
	_c.Call.Return(run)
	return _c
}

// Initialize provides a mock function for the type MockDialector
func (_mock *MockDialector) Initialize(dB *gorm.DB) error {
	ret := _mock.Called(dB)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) error); ok {
		r0 = returnFunc(dB)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDialector_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockDialector_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - dB *gorm.DB
func (_e *MockDialector_Expecter) Initialize(dB interface{}) *MockDialector_Initialize_Call {
	return &MockDialector_Initialize_Call{Call: _e.mock.On("Initialize", dB)}
}

func (_c *MockDialector_Initialize_Call) Run(run func(dB *gorm.DB)) *MockDialector_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDialector_Initialize_Call) Return(err error) *MockDialector_Initialize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDialector_Initialize_Call) RunAndReturn(run func(dB *gorm.DB) error) *MockDialector_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// Migrator provides a mock function for the type MockDialector
func (_mock *MockDialector) Migrator(db *gorm.DB) gorm.Migrator {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for Migrator")
	}

	var r0 gorm.Migrator
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) gorm.Migrator); ok {
		r0 = returnFunc(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gorm.Migrator)
		}
	}
	return r0
}

// MockDialector_Migrator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrator'
type MockDialector_Migrator_Call struct {
	*mock.Call
}

// Migrator is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockDialector_Expecter) Migrator(db interface{}) *MockDialector_Migrator_Call {
	return &MockDialector_Migrator_Call{Call: _e.mock.On("Migrator", db)}
}

func (_c *MockDialector_Migrator_Call) Run(run func(db *gorm.DB)) *MockDialector_Migrator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDialector_Migrator_Call) Return(migrator gorm.Migrator) *MockDialector_Migrator_Call {
	_c.Call.Return(migrator)
	return _c
}

func (_c *MockDialector_Migrator_Call) RunAndReturn(run func(db *gorm.DB) gorm.Migrator) *MockDialector_Migrator_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockDialector
func (_mock *MockDialector) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDialector_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDialector_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDialector_Expecter) Name() *MockDialector_Name_Call {
	return &MockDialector_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDialector_Name_Call) Run(run func()) *MockDialector_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDialector_Name_Call) Return(s string) *MockDialector_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDialector_Name_Call) RunAndReturn(run func() string) *MockDialector_Name_Call {
	_c.Call.Return(run)
	return _c
}

// QuoteTo provides a mock function for the type MockDialector
func (_mock *MockDialector) QuoteTo(writer clause.Writer, s string) {
	_mock.Called(writer, s)
	return
}

// MockDialector_QuoteTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuoteTo'
type MockDialector_QuoteTo_Call struct {
	*mock.Call
}

// QuoteTo is a helper method to define mock.On call
//   - writer clause.Writer
//   - s string
func (_e *MockDialector_Expecter) QuoteTo(writer interface{}, s interface{}) *MockDialector_QuoteTo_Call {
	return &MockDialector_QuoteTo_Call{Call: _e.mock.On("QuoteTo", writer, s)}
}

func (_c *MockDialector_QuoteTo_Call) Run(run func(writer clause.Writer, s string)) *MockDialector_QuoteTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 clause.Writer
		if args[0] != nil {
			arg0 = args[0].(clause.Writer)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDialector_QuoteTo_Call) Return() *MockDialector_QuoteTo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDialector_QuoteTo_Call) RunAndReturn(run func(writer clause.Writer, s string)) *MockDialector_QuoteTo_Call {
	_c.Run(run)
	return _c
}
