// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"
)

type Article struct {
	ID        int32
	Slug      sql.NullString
	Title     string
	Summary   sql.NullString
	Content   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
