// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package storage

import (
	"context"
	"database/sql"
)

const deleteArticle = `-- name: DeleteArticle :exec
UPDATE articles
SET deleted_at = CURRENT_TIMESTAMP, slug = null
WHERE slug = ?
`

func (q *Queries) DeleteArticle(ctx context.Context, slug sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, slug)
	return err
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, slug, title, summary, content, created_at, updated_at, deleted_at
FROM articles
WHERE id = LAST_INSERT_ID()
`

func (q *Queries) GetArticleByID(ctx context.Context) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticleByID)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT id, slug, title, summary, content, created_at, updated_at, deleted_at
FROM articles
WHERE slug = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetArticleBySlug(ctx context.Context, slug sql.NullString) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArticleBySlugForUpdate = `-- name: GetArticleBySlugForUpdate :one
SELECT id, slug, title, summary, content, created_at, updated_at, deleted_at
FROM articles
WHERE slug = ? AND deleted_at IS NULL
`

func (q *Queries) GetArticleBySlugForUpdate(ctx context.Context, slug sql.NullString) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticleBySlugForUpdate, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertArticle = `-- name: InsertArticle :exec
INSERT INTO articles (slug, title, summary, content, created_at, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type InsertArticleParams struct {
	Slug    sql.NullString
	Title   string
	Summary sql.NullString
	Content sql.NullString
}

func (q *Queries) InsertArticle(ctx context.Context, arg InsertArticleParams) error {
	_, err := q.db.ExecContext(ctx, insertArticle,
		arg.Slug,
		arg.Title,
		arg.Summary,
		arg.Content,
	)
	return err
}

const updateArticle = `-- name: UpdateArticle :exec
UPDATE articles
SET title = ?, summary = ?, content = ?
WHERE slug = ? AND deleted_at IS NULL
`

type UpdateArticleParams struct {
	Title   string
	Summary sql.NullString
	Content sql.NullString
	Slug    sql.NullString
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) error {
	_, err := q.db.ExecContext(ctx, updateArticle,
		arg.Title,
		arg.Summary,
		arg.Content,
		arg.Slug,
	)
	return err
}
