package models

import "time"

// Article is the shape of an article that the transport layer consumes
// and the database returns. it mirrors the SQL schema defined in
// storage/queries.sql (generated by sqlc).
//
// We expose JSON tags for API serialization but do not rely on any ORM
// annotations.
type Article struct {
	ID        uint       `json:"id"`
	Slug      string     `json:"slug"`
	Title     string     `json:"title"`
	Summary   string     `json:"summary"`
	Content   string     `json:"content"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}
